#define HASP_NUM_PAGES 12

#define TAG_ATTR 2
#define TAG_MSGR 3

#define HASP_VERSION_MAJOR 0
#define HASP_VERSION_MINOR 0
#define HASP_VERSION_REVISION 1

#define HASP_SLEEP_OFF 0
#define HASP_SLEEP_SHORT 1
#define HASP_SLEEP_LONG 2

#define HASP_USE_SPIFFS 0
#define HASP_USE_LITTLEFS 0